openapi: 3.0.4
info:
  title: Ask exchange log models
  description: Log models for logging services of ask exchange
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonQuestionLogModel:
      title: Common log model
      description: Common question log model for all microservices
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        questionContext:
          $ref: '#/components/schemas/QuestionContextLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    QuestionContextLogModel:
      title: question context model for log
      type: object
      properties:
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
        questionRequestLog:
          $ref: '#/components/schemas/QuestionLog'
        questionResponseLog:
          $ref: '#/components/schemas/QuestionLog'


    CommonAnswerLogModel:
      title: Common log model
      description: Common answer log model for all microservices
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        answerContext:
          $ref: '#/components/schemas/AnswerContextLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    AnswerContextLogModel:
      title: answer context model for log
      type: object
      properties:
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
        answerRequestLog:
          $ref: '#/components/schemas/AnswerLog'
        answerResponseLog:
          $ref: '#/components/schemas/AnswerLog'


    QuestionLog:
      title: Question model for a log
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        parentUserId:
          type: string

    AnswerLog:
      title: Answer model for a log
      type: object
      properties:
        id:
          type: string
        body:
          type: string
        date:
          type: string
        likes:
          type: string
        parentUserId:
          type: string
        parentQuestionId:
          type: string

    ErrorLogModel:
      title: Error model for a log
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string




