ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.shirnin.askexchange.app.ApplicationKt.module
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
    - "http://192.168.0.182:8080/"
  watch:
    - classes
    - resources
repository:
  test: "in-memory"
  #prod: inmemory
  # prod: cassandra
  prod: psql
  psql:
    user: postgres
    password: postgres
    url: "jdbc:postgresql://psql:5432/askexchange"
    schema: askexchange

jwt:
  secret: "secret1"
  issuer: "AskExchangeKotlin"
  audience: "askexch-users"
  realm: "asxexch"
  clientId: "askexch-service"